### ISSUE TITLE
Can't open tablet driver

### ISSUE THREAD

**Issue by shun233** [hawku/TabletDriver#612]
When I first open the GUI, I forgot to download the required software, but after I finish downloading the software, I try opening it, but it won't turn on.
I found two error codes form event viewer.
error code1:
Faulting application name: TabletDriverGUI.exe, version: 1.0.0.0, time stamp: 0x5c1636b3
Faulting module name: KERNELBASE.dll, version: 10.0.18362.535, time stamp: 0x5bd9df62
Exception code: 0xe0434352
Fault offset: 0x001135d2
Faulting process id: 0xab8
Faulting application start time: 0x01d609e603b27667
Faulting application path: C:\Users\jarve\Downloads\TabletDriverV0.2.3\TabletDriverGUI.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: c9fa8011-1b41-452f-9a42-d2afb759c18f
Faulting package full name: 
Faulting package-relative application ID: 

error code2:

Application: TabletDriverGUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at TabletDriverGUI.MainWindow.InitializeComponent()
   at TabletDriverGUI.MainWindow..ctor()
   at TabletDriverGUI.App..ctor()
   at TabletDriverGUI.App.Main()

## Hardware/software information
Windows Version: Windows 10 64 bit

Tablet Driver version: 0.23
Tablet model: gaomons620

**Comment by Vlothx** [comment]
Hello, looks like Hawku stopped the development of this driver. I would recommend trying [this fork](https://github.com/InfinityGhost/TabletDriver). You might need to disable your antivirus, or if don't want to do that, you can compile it by yourself.
